### PR TITLE
Fix windows compatibility

### PR DESCRIPTION
**Pull request by ioncodes**
Make it compatible with Windows by checking the OS first and then setting the name to either "capstone" or "libcapstone". "capstone" is for Windows.

### CODE REVIEW

**Comment by parasyte** [comment]
@ioncodes Thanks for the contribution! Unfortunately, your editor changed all of the line endings on the two edited files. If you could save these both with "unix line endings" (aka LF) and commit the change to your branch, I would be happy to review and merge this. :)

**Comment by ioncodes** [comment]
Ooops, I'll change that now!

**Comment by ioncodes** [comment]
There ya go :)

**Comment by parasyte** [comment]
Nice, thanks!

**Comment by parasyte** [comment]
Cheers!

**Pull request merged**
